### ISSUE TITLE
SDK doesn't handle spaces in the target name

### ISSUE THREAD

**Issue by sprejjs** [CriticalMoments/CriticalMoments#110]
Hi Steve,

Just started integrating your SDK into the app, seems really powerful!

I was getting an exception when trying to launch the app after integrating your SDK because I had a space character in the target name. Looks like you are fetching the config path with this code: `localConfigUrl.absoluteString` which escapes the space character with `%20`, however, when you pass it down `[_appcore start:allowDebugLoad error:&error];` it throws an exception `.../cmDevConfig.json: no such file or directory` as it cannot handle escaped path under the hood.

I've renamed my target, so I'm not blocked by this, but it may trip some less experienced folks.

**Comment by scosman** [comment]
Great catch. Will fix this in the next release. Thanks!
